#!/usr/bin/python3
def raise_excepion():
    raise TypeError("Exception has been raised")
